<?php
/**
 * Product Seeder — Inserts all 38 products from the frontend data into MySQL.
 * 
 * Usage: php seed_products.php
 * Safe to re-run: uses INSERT IGNORE to skip duplicates.
 */

require_once __DIR__ . '/config/database.php';

$db = getDB();

// All products from src/data/products.ts
$products = [
    // ─── SWEETS ───
    [
        'name' => 'Nethi Sunnunda',
        'slug' => 'nethi-sunnunda',
        'description' => 'Traditional urad dal sweet with pure ghee',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 1000,
        'image' => '/images/nethi-sunnunda.jpg',
        'rating' => 4.9,
        'bestseller' => 1,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 300],
            ['weight' => '500g', 'price' => 550],
            ['weight' => '1kg', 'price' => 1000],
        ],
    ],
    [
        'name' => 'Nethi Sunnunda with Badham',
        'slug' => 'nethi-sunnunda-badam',
        'description' => 'Premium sunnunda enriched with almond pieces',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 1100,
        'image' => '/images/badam-sunnunda.jpg',
        'rating' => 4.9,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 350],
            ['weight' => '500g', 'price' => 600],
            ['weight' => '1kg', 'price' => 1100],
        ],
    ],
    [
        'name' => 'Seeds with Dry Fruits Bite',
        'slug' => 'dry-fruit-bite',
        'description' => 'Healthy energy bars made with seeds and dry fruits',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 1200,
        'image' => '/images/dry-fruit-bite.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 400],
            ['weight' => '500g', 'price' => 700],
            ['weight' => '1kg', 'price' => 1200],
        ],
    ],
    [
        'name' => 'Dry Fruit Healthy Laddu',
        'slug' => 'dry-fruit-laddu',
        'description' => 'Power-packed laddu with mixed dry fruits',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 1200,
        'image' => '/images/dry-fruit-laddu.jpg',
        'rating' => 4.9,
        'bestseller' => 1,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 400],
            ['weight' => '500g', 'price' => 700],
            ['weight' => '1kg', 'price' => 1200],
        ],
    ],
    [
        'name' => 'Raggi Nethi Laddu',
        'slug' => 'ragi-nethi-laddu',
        'description' => 'Healthy finger millet laddu with pure ghee',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 900,
        'image' => '/images/ragi-nethi-laddu.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 300],
            ['weight' => '500g', 'price' => 500],
            ['weight' => '1kg', 'price' => 900],
        ],
    ],
    [
        'name' => 'Nuvvula Chikki',
        'slug' => 'nuvvula-chikki',
        'description' => 'Nutritious sesame seed chikki',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 600,
        'image' => '/images/nuvvula-chikki.jpg',
        'rating' => 4.6,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 600],
        ],
    ],
    [
        'name' => 'Nuvvula Laddu',
        'slug' => 'nuvvula-laddu',
        'description' => 'Health-conscious sesame balls',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 750,
        'image' => '/images/nuvvula-laddu.jpg',
        'rating' => 4.6,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 250],
            ['weight' => '500g', 'price' => 450],
            ['weight' => '1kg', 'price' => 750],
        ],
    ],
    [
        'name' => 'Palli Chikki',
        'slug' => 'palli-chikki',
        'description' => 'Classic peanut brittle',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 600,
        'image' => '/images/palli-chikki.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 600],
        ],
    ],
    [
        'name' => 'Boondhi Chikki',
        'slug' => 'boondhi-chikki',
        'description' => 'Crispy sweet boondhi bars',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 600,
        'image' => '/images/boondhi-chikki.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 600],
        ],
    ],
    [
        'name' => 'Kajji Kayalu',
        'slug' => 'kajji-kayalu',
        'description' => 'Crispy fried sweet dumplings with coconut filling',
        'category' => 'sweets',
        'weight' => '1kg',
        'price' => 800,
        'image' => '/images/kajji-kayalu.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 250],
            ['weight' => '500g', 'price' => 450],
            ['weight' => '1kg', 'price' => 800],
        ],
    ],

    // ─── SNACKS ───
    [
        'name' => 'Gavalu',
        'slug' => 'gavalu',
        'description' => 'Sweet shell-shaped traditional treats',
        'category' => 'snacks',
        'weight' => '1kg',
        'price' => 600,
        'image' => '/images/gavalu-v3.jpg',
        'rating' => 4.6,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 600],
        ],
    ],
    [
        'name' => 'Ribbon Pakoda',
        'slug' => 'ribbon-pakoda',
        'description' => 'Crispy, ribbon-shaped savory snack',
        'category' => 'snacks',
        'weight' => '1kg',
        'price' => 500,
        'image' => '/images/ribbon-pakodi.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 350],
            ['weight' => '1kg', 'price' => 500],
        ],
    ],
    [
        'name' => 'Chakralu',
        'slug' => 'chakralu',
        'description' => 'Traditional crunch spiral snacks',
        'category' => 'snacks',
        'weight' => '1kg',
        'price' => 500,
        'image' => '/images/chakralu.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 350],
            ['weight' => '1kg', 'price' => 500],
        ],
    ],
    [
        'name' => 'Karam Bundhi',
        'slug' => 'karam-bundhi',
        'description' => 'Spicy and crispy boondhi',
        'category' => 'snacks',
        'weight' => '1kg',
        'price' => 500,
        'image' => '/images/kaju-bundhi.jpg',
        'rating' => 4.6,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 350],
            ['weight' => '1kg', 'price' => 500],
        ],
    ],
    [
        'name' => 'Sanna Karampusa',
        'slug' => 'sanna-karampusa',
        'description' => 'Thin, spicy gram flour sev',
        'category' => 'snacks',
        'weight' => '1kg',
        'price' => 600,
        'image' => '/images/sanna-karam-pusa.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 600],
        ],
    ],
    [
        'name' => 'Minapa Chakralu',
        'slug' => 'minapa-chakralu',
        'description' => 'Crispy urad dal spirals',
        'category' => 'snacks',
        'weight' => '1kg',
        'price' => 500,
        'image' => '/images/minapa-chakralu.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 350],
            ['weight' => '1kg', 'price' => 500],
        ],
    ],
    [
        'name' => 'Palli Pakodi (Peanut)',
        'slug' => 'palli-pakodi',
        'description' => 'Spicy peanut pakodi',
        'category' => 'snacks',
        'weight' => '1kg',
        'price' => 600,
        'image' => '/images/palli-pakodi-v2.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 600],
        ],
    ],

    // ─── PICKLES (VEG) ───
    [
        'name' => 'Kakarakaya Pickle',
        'slug' => 'kakarakaya-pickle',
        'description' => 'Traditional bitter gourd pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/kakaragaya-pickle.jpg',
        'rating' => 4.5,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],
    [
        'name' => 'Kotimeera Pickle',
        'slug' => 'kotimeera-pickle',
        'description' => 'Flavorful coriander leaves pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/kotimera-pickle.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],
    [
        'name' => 'Pandu Mirchi Pickle',
        'slug' => 'pandu-mirchi-pickle',
        'description' => 'Fiery red chili pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/pandu-mirchi.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],
    [
        'name' => 'Tomato Pickle',
        'slug' => 'tomato-pickle',
        'description' => 'Tangy and spicy tomato pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/tamota-pickle.jpg',
        'rating' => 4.6,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],
    [
        'name' => 'Gongura Pickle',
        'slug' => 'gongura-pickle',
        'description' => 'Classic Andhra sorrel leaves pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/gongura-pickle.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],
    [
        'name' => 'Vankaya Pickle',
        'slug' => 'vankaya-pickle',
        'description' => 'Unique and spicy brinjal (eggplant) pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/vankaya-pickle.jpg',
        'rating' => 4.5,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],
    [
        'name' => 'Mango Pickle',
        'slug' => 'mango-pickle',
        'description' => 'Zesty raw mango pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/mango-pickle.jpg',
        'rating' => 4.9,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],
    [
        'name' => 'Mamidi Alam',
        'slug' => 'mamidi-alam',
        'description' => 'Mango-ginger blend pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/ginger-pickle.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],
    [
        'name' => 'Alam Pickle',
        'slug' => 'alam-pickle',
        'description' => 'Zesty ginger pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 596,
        'image' => '/images/ginger-pickle.jpg',
        'rating' => 4.6,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 200],
            ['weight' => '500g', 'price' => 400],
            ['weight' => '1kg', 'price' => 596],
        ],
    ],

    // ─── PICKLES (NON-VEG) ───
    [
        'name' => 'Chicken with Bone',
        'slug' => 'chicken-bone-pickle',
        'description' => 'Spicy chicken pickle with bone pieces',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 1040,
        'image' => '/images/chicken-pickle.jpg',
        'rating' => 4.9,
        'bestseller' => 1,
        'is_veg' => 0,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 300],
            ['weight' => '500g', 'price' => 550],
            ['weight' => '1kg', 'price' => 1040],
        ],
    ],
    [
        'name' => 'Chicken Boneless',
        'slug' => 'chicken-boneless-pickle',
        'description' => 'Premium boneless chicken pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 1200,
        'image' => '/images/chicken-pickle.jpg',
        'rating' => 5.0,
        'bestseller' => 1,
        'is_veg' => 0,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 350],
            ['weight' => '500g', 'price' => 650],
            ['weight' => '1kg', 'price' => 1200],
        ],
    ],
    [
        'name' => 'Chicken Gongura Pickle',
        'slug' => 'chicken-gongura-pickle',
        'description' => 'Combo of spicy chicken and tangy gongura',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 1396,
        'image' => '/images/chicken-pickle.jpg',
        'rating' => 4.9,
        'bestseller' => 0,
        'is_veg' => 0,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 400],
            ['weight' => '500g', 'price' => 750],
            ['weight' => '1kg', 'price' => 1396],
        ],
    ],
    [
        'name' => 'Prawn Gongura Pickle',
        'slug' => 'prawn-gongura-pickle',
        'description' => 'Exotic prawn pickle with gongura flavor',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 1960,
        'image' => '/images/non-veg-pickles.jpg',
        'rating' => 4.9,
        'bestseller' => 0,
        'is_veg' => 0,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 550],
            ['weight' => '500g', 'price' => 1000],
            ['weight' => '1kg', 'price' => 1960],
        ],
    ],
    [
        'name' => 'Prawn Pickle',
        'slug' => 'prawn-pickle',
        'description' => 'Delicious and spicy prawn pickle',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 1800,
        'image' => '/images/non-veg-pickles.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 0,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 500],
            ['weight' => '500g', 'price' => 950],
            ['weight' => '1kg', 'price' => 1800],
        ],
    ],
    [
        'name' => 'Mutton pickle',
        'slug' => 'mutton-pickle',
        'description' => 'Premium mutton pickle with rich spices',
        'category' => 'pickles',
        'weight' => '1kg',
        'price' => 2076,
        'image' => '/images/non-veg-pickles.jpg',
        'rating' => 5.0,
        'bestseller' => 0,
        'is_veg' => 0,
        'is_homemade' => 1,
        'variants' => [
            ['weight' => '250g', 'price' => 600],
            ['weight' => '500g', 'price' => 1100],
            ['weight' => '1kg', 'price' => 2076],
        ],
    ],

    // ─── SPICES ───
    [
        'name' => 'Kobbari Karam',
        'slug' => 'kobbari-karam',
        'description' => 'Coconut spice powder',
        'category' => 'spices',
        'weight' => '250g',
        'price' => 219,
        'image' => '/images/kobbari-karam.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [['weight' => '250g', 'price' => 219]],
    ],
    [
        'name' => 'Nalla Karam',
        'slug' => 'nalla-karam',
        'description' => 'Black spice powder with secret ingredients',
        'category' => 'spices',
        'weight' => '250g',
        'price' => 219,
        'image' => '/images/nalla-karam.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [['weight' => '250g', 'price' => 219]],
    ],
    [
        'name' => 'KarvePaku Karam',
        'slug' => 'karivepaku-karam',
        'description' => 'Nutritious curry leaves spice powder',
        'category' => 'spices',
        'weight' => '250g',
        'price' => 219,
        'image' => '/images/karivepaku-karam.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [['weight' => '250g', 'price' => 219]],
    ],
    [
        'name' => 'Masala karam',
        'slug' => 'masala-karam',
        'description' => 'Rich blended spice powder',
        'category' => 'spices',
        'weight' => '250g',
        'price' => 219,
        'image' => '/images/guntur-karam.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [['weight' => '250g', 'price' => 219]],
    ],
    [
        'name' => 'Munagaku Karam',
        'slug' => 'munagaku-karam',
        'description' => 'Healthy drumstick leaves spice powder',
        'category' => 'spices',
        'weight' => '250g',
        'price' => 219,
        'image' => '/images/munagaku-karam.jpg',
        'rating' => 4.7,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [['weight' => '250g', 'price' => 219]],
    ],
    [
        'name' => 'Velluli Karam',
        'slug' => 'velluli-karam',
        'description' => 'Flavorful garlic spice powder',
        'category' => 'spices',
        'weight' => '250g',
        'price' => 219,
        'image' => '/images/velluli-karam.jpg',
        'rating' => 4.8,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [['weight' => '250g', 'price' => 219]],
    ],
    [
        'name' => 'Pasupu',
        'slug' => 'pasupu',
        'description' => 'Pure and traditional turmeric powder',
        'category' => 'spices',
        'weight' => '250g',
        'price' => 140,
        'image' => '/images/turmeric-pasupu.jpg',
        'rating' => 4.9,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [['weight' => '250g', 'price' => 140]],
    ],
    [
        'name' => 'Chilly powder',
        'slug' => 'chilly-powder',
        'description' => 'High-quality spice chilly powder',
        'category' => 'spices',
        'weight' => '250g',
        'price' => 189,
        'image' => '/images/guntur-karam.jpg',
        'rating' => 4.9,
        'bestseller' => 0,
        'is_veg' => 1,
        'is_homemade' => 1,
        'variants' => [['weight' => '250g', 'price' => 189]],
    ],
];

// ─── INSERT ───
$stmt = $db->prepare("
    INSERT IGNORE INTO products (name, slug, description, category, weight, price, image, rating, bestseller, is_veg, is_homemade, variants, status)
    VALUES (:name, :slug, :description, :category, :weight, :price, :image, :rating, :bestseller, :is_veg, :is_homemade, :variants, 'active')
");

$inserted = 0;
$skipped = 0;

foreach ($products as $p) {
    $stmt->execute([
        'name'        => $p['name'],
        'slug'        => $p['slug'],
        'description' => $p['description'],
        'category'    => $p['category'],
        'weight'      => $p['weight'],
        'price'       => $p['price'],
        'image'       => $p['image'],
        'rating'      => $p['rating'],
        'bestseller'  => $p['bestseller'],
        'is_veg'      => $p['is_veg'],
        'is_homemade' => $p['is_homemade'],
        'variants'    => json_encode($p['variants']),
    ]);

    if ($stmt->rowCount() > 0) {
        $inserted++;
    } else {
        $skipped++;
    }
}

echo "✅ Seeding complete!\n";
echo "   Inserted: $inserted\n";
echo "   Skipped (already exists): $skipped\n";
echo "   Total in DB: " . $db->query("SELECT COUNT(*) FROM products")->fetchColumn() . "\n";
